dormyboba:
  domain: 127.0.0.1:8000
  vk_token: 'vk1.a.BeBAXubULCb42UFTGBuIr1nXoIsVyaj-PPkzss2VGyg2EbM5FLEtLmOr0u6etVppiPHihSoeDJLpXlu_Janb6ZRAHF9nFL7wLNsZszWnLUoV2-2mE5JiPK9vr0nGFwXySTI7CRxow-waRGJGDI9G5KlbU_U1bl_IqB5S5PcGEbdAWg6pF_15AlzOSxPAzKoFin5sCBydfapveQWpYd2nQw'
  group_id: -223616799
  postgres:
    user: 'postgres'
    password: '123456'
    host: 'postgresql'
    db: 'dormyboba'
  gc:
    defect_sheet_id: '1MdSCTsskQlQwMoPaT__gbeiimFG8R-A-24DbmU0jf88'
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCavEZKxOgOhAOM
    N0aGV4I5QYFBf/rmAFXJB+AL/kHkSgtKtTF0BUwwNn25SLm2t6++tIJhzTqZEKW3
    BWnHC7AnLLmtHDWutqCj2rpPvMM6WLUFE2KzNFmUFmFuaQu+Trfvfr52GlCOJD6k
    OJdXwxmMuXBeboBUEWxci0kN9nhKufe2P1rWI41FhDvFcR3vLx5erk7grBIQQfZQ
    U4u3YuvnkbctK954FPnDCfFG55bvO4/9wEDluwhZU8H+/f458haJvPMtagJBY3xh
    Aqnej+/0qvhb52f6YTUHGwN5u9YbJJm6H6hq7XAqrWqwILEERTnqIWjk54EaNkSJ
    CF8t3hgRAgMBAAECggEAQsE97AzV9kkyxJ+mL9f56NyfOFRPuEFlwQRCPrpSz/u3
    smPIMX8FlvkzNSewYykMy0/RvgLNqHJbo8FUmJgsx0HO2uWELVtBo17+KN9NNFNH
    yShLWPeZO7+KChmMhO4uAUcjQQ1qOmBdm/iEJksXrzPjTAINH/eiUayPeFQgIlA7
    m4gIFGaZI7IvSpinhy31c5WWTqKzpHpE5XOfR+EMu6LiCYZA836o7EtCbIC1+uDG
    seEVpSfFXYL50inhtcfhDTM9gfqCfqbDsmFEB38Gx0uQ6v23fVd+euXWybBARpgT
    p2abD0vA+ccqexHWmrChskCEBSCwKTo8wtggut+mjwKBgQDRzpKucKC2sWUbCCjt
    YwFtL/UteVNJK2lzeVatJqBxOriy0Jq4AE3k7lPTfvUnHj1IUOA68hRt/tDL1Q4Y
    M9j6Vt3+u2I25hjRxlh1X8eyNiqVISForKC6CMoPGqPQ++FhtFw6T6hClu3xSpay
    zjcaBM04NbvpxY1dKN4uEaY0MwKBgQC8za/kKczVxSTPRQ2ty1VJMAkkC6qPy4/l
    VOvCTC21qbthX7hGTQtaNx4eLnyvLIEByGlcQsO2c42Q2SI4NruqY3acIr/09c60
    LGHm37ffctSlZOp9xCXGF3rm6W1EhJwnUTvvh/4oQwyXxH1jP8XgPDsxaEW3DJCe
    tpXvJhfeqwKBgQCvM0hr4ONkDDj43NSIf1+mlSCxS5pQBK93XUETMKlURIwNzoMU
    2jQx0w8vEtqXQvo71EWbE6IZxGsJe63cahdr3XReDo5Sd80MCAzAXy48VF000Ui7
    x0Qkdch92monzt6Dn4BQtUo16SFjmDzFrcx3rsDMipqT+YM14zW91MEs3wKBgB9Z
    f/VAw5RTUdNgwe6zrouigEIN9do+kLwhp6vxfj2F22lFvZFexZ3LPSMB0Q49M4aa
    QnRhWaH3+e+tPjNbUzntngo68ui30AS2weLWDu/5Xzm/UfhkE2mbCHtDEzOnWU5l
    /K+/QwJob7TbmX5bXn3nQmTnzXuhiHnyE19MUfZVAoGBAJ1U3pZN97CPsznKy7eH
    rtpUVSwNupb/6kPucp7i9gogag3kGFq05ImE+ozPs93rCPjPmyb1wupcvI0aCIwD
    IgKhFiV9CxSmlN17FJlJidTefm+GtlE6ClAqrQZqZbFKEfairzoPWc3Ez4A3GhZY
    hErkn8wRKMZYPp0uy9gZNl5V
    -----END PRIVATE KEY-----
