name: Integration

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./tests/integration/features/steps/docker-compose.yml"
        env:
          CORE_IMAGE: ghcr.io/${{ github.repository_owner }}/dormyboba_core:${{ github.sha }}
      # - name: Login to GHCR
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
